from Bio import AlignIO
'''			For single alignment

alignment=AlignIO.read(open("PF18225_seed.txt"),"stockholm")
print("Alignment read:")
print(alignment)
print("\n\nPrinting sequences\n")
for align in alignment:
	print(align.seq)
'''
#for multiple alignments
alignment=AlignIO.parse(open("PF18225_seed.txt"),"stockholm")
print("Alignment read with parse")
print(alignment)

for align in alignment:
	print(align)

###pairwise sequence alignment
from Bio import pairwise2
from Bio.Seq import Seq
print("Demonstrating BioPython pairwise alignment")
seq1=Seq('ACCGGT')
seq2=Seq('ACGT')
alignments=pairwise2.align.globalxx(seq1,seq2)

for align in alignments:
	print(align)
##better visualization
from Bio.pairwise2 import format_alignment
for align in alignments:
	print(format_alignment(*align))
#### using Align module

from Bio import Align
aligner=Align.PairwiseAligner()
print("Using now Align module")
print("Aligner:")
print(aligner)

###example using the clustalw2 command, download it from www.clustal.org/download/current
from Bio.Align.Applications import ClustalwCommandline
cmd=ClustalwCommandline("clustalw2",infile="opuntia.fasta")
print(cmd)
cmd()  #runs command and generates .aln and .dnd files(opuntia)

align=AlignIO.read("opuntia.aln","clustal")
print("Read align from opuntia.aln generated by clustal")
print(align)
print("Printing alignments")

for a in align:
	print(a.seq)
print("Print[0][1]of align\n")
print(align[0].seq)
print(align[1].seq)


alignments=pairwise2.align.globalxx(align[0].seq,align[1].seq)
for a in alignments:
	print(format_alignment(*a))



